/************
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

************************/


import java.util.*;
class Solution {
    public char findTheDifference(String s, String t) {
       Map<Character,Integer> map = new HashMap<>();
        int n;
        n = Math.min(s.length(),t.length());
        int sum=0,i=0;
        boolean sgreat =false;
        if(s.length() > t.length())
            sgreat =true;
        while(i<n)
        {
            if(sgreat)
            sum  += ((s.charAt(i)-0) - (t.charAt(i)-0));
            else
                sum  += ((t.charAt(i)-0) - (s.charAt(i)-0));
            i++;
        System.out.println(sum);
        }
        if(s.length()>t.length() && s.charAt(i)!='\0' && i==n)
        {
            sum = sum + (s.charAt(i)-'0');
        }
        System.out.println(t.charAt(i)-0);
        if(t.length() > s.length() && t.charAt(i)!='\0' && i == n)
        {
            sum += (t.charAt(i)-0); 
            System.out.println(sum);
        }
        System.out.println(sum);
        return (char)(sum);
    }
}
